(function(){if(!this.clearbitRequire){var c={},m={},n=function(g,a){var e=h(a,g),b=h(e,"./index");if(a=m[e]||m[b])return a;if(b=c[e]||c[e=b])return a={id:e,exports:{}},m[e]=a.exports,b(a.exports,function(b){return n(b,e.split("/").slice(0,-1).join("/"))},a),m[e]=a.exports;throw"module "+g+" not found";},h=function(g,a){var e=[];g=/^\.\.?(\/|$)/.test(a)?[g,a].join("/").split("/"):a.split("/");for(var b=0,f=g.length;b<f;b++)a=g[b],".."==a?e.pop():"."!=a&&""!=a&&e.push(a);return e.join("/")};this.clearbitRequire=
function(g){return n(g,"")};this.clearbitRequire.define=function(g){for(var a in g)c[a]=g[a]};this.clearbitRequire.modules=c;this.clearbitRequire.cache=m}return this.clearbitRequire}).call(this);
this.clearbitRequire.define({"risk/fingerprint":function(c,m,n){(function(){var h=m("./fontdetect");var g=function(){function a(){}a.calculate=function(e){return(new this).calculate(e)};a.prototype.calculate=function(e){var b=this.getProperties();return this.getBattery(function(f){b.battery=f;return e(b)})};a.prototype.getCanvasPrint=function(){var e=document.createElement("canvas");var b=null;try{b=e.getContext("2d")}catch(f){return}b.textBaseline="top";b.font="14px 'Arial'";b.textBaseline="alphabetic";
b.fillStyle="#f60";b.fillRect(125,1,62,20);b.fillStyle="#069";b.fillText("Fingerprint 1.0",2,15);b.fillStyle="rgba(102, 204, 0, 0.7)";b.fillText("Fingerprint 1.0",4,17);return e.toDataURL()};a.prototype.isSupportedCodec=function(e){if(window.MediaSource)return window.MediaSource.isTypeSupported(e);if(window.WebKitMediaSource)return window.WebKitMediaSource.isTypeSupported(e)};a.prototype.getCodecs=function(){var e;var b=['video/mp4; codecs="avc1.42c00d"','video/ogg; codecs="theora"','video/webm; codecs="vorbis,vp8"',
'video/webm; codecs="vorbis,vp9"','video/mp2t; codecs="avc1.42E01E,mp4a.40.2"'];var f='audio/mpeg,audio/mp4; codecs="mp4a.40.2",audio/ogg; codecs="vorbis",audio/ogg; codecs="opus",audio/webm; codecs="vorbis",audio/wav; codecs="1"'.split(",");b=function(){var d;var f=[];var a=0;for(d=b.length;a<d;a++)e=b[a],this.isSupportedCodec(e)&&f.push(e);return f}.call(this);f=function(){var b;var a=[];var k=0;for(b=f.length;k<b;k++)e=f[k],this.isSupportedCodec(e)&&a.push(e);return a}.call(this);return{audio:f,
video:b}};a.prototype.fontTypes="Abadi MT Condensed Light;Adobe Fangsong Std;Adobe Hebrew;Adobe Ming Std;Agency FB;Arab;Arabic Typesetting;Arial Black;Batang;Bauhaus 93;Bell MT;Bitstream Vera Serif;Bodoni MT;Bookman Old Style;Braggadocio;Broadway;Calibri;Californian FB;Castellar;Casual;Centaur;Century Gothic;Chalkduster;Colonna MT;Copperplate Gothic Light;DejaVu LGC Sans Mono;Desdemona;DFKai-SB;Dotum;Engravers MT;Eras Bold ITC;Eurostile;FangSong;Forte;Franklin Gothic Heavy;French Script MT;Gabriola;Gigi;Gisha;Goudy Old Style;Gulim;GungSeo;Haettenschweiler;Harrington;Hiragino Sans GB;Impact;Informal Roman;KacstOne;Kino MT;Kozuka Gothic Pr6N;Lohit Gujarati;Loma;Lucida Bright;Lucida Fax;Magneto;Malgun Gothic;Matura MT Script Capitals;Menlo;MingLiU-ExtB;MoolBoran;MS PMincho;MS Reference Sans Serif;News Gothic MT;Niagara Solid;Nyala;Palace Script MT;Papyrus;Perpetua;Playbill;PMingLiU;Rachana;Rockwell;Sawasdee;Script MT Bold;Segoe Print;Showcard Gothic;SimHei;Snap ITC;TlwgMono;Tw Cen MT Condensed Extra Bold;Ubuntu;Umpush;Univers;Utopia;Vladimir Script;Wide Latin".split(";");
a.prototype.getCSSFonts=function(){var e;var b=new h;var a=this.fontTypes;var d=[];var l=0;for(e=a.length;l<e;l++){var k=a[l];b.detect(k)&&d.push(k)}return d};a.prototype.getNavigatorProperties=function(){var e;var b={};var a=window.navigator;for(e in a){var d=a[e];"object"!==typeof d&&"function"!==typeof d&&(b[e]=d)}return b};a.prototype.getRegularPlugins=function(){var a,b;var f=[];var d=navigator.plugins;var l=0;for(a=d.length;l<a;l++){var k=d[l];var g={name:k.name,filename:k.filename,description:k.description,
version:k.version,mimeTypes:[]};var h=0;for(b=k.length;h<b;h++){var c=k[h];g.mimeTypes.push({description:c.description,suffixes:c.suffixes,type:c.type})}f.push(g)}return f};a.prototype.getIEPlugins=function(){var a;var b=[];var f="AcroPDF.PDF;Adodb.Stream;AgControl.AgControl;DevalVRXCtrl.DevalVRXCtrl.1;MacromediaFlashPaper.MacromediaFlashPaper;Msxml2.DOMDocument;Msxml2.XMLHTTP;PDF.PdfCtrl;QuickTime.QuickTime;QuickTimeCheckObject.QuickTimeCheck.1;RealPlayer;RealPlayer.RealPlayer(tm) ActiveX Control (32-bit);RealVideo.RealVideo(tm) ActiveX Control (32-bit);Scripting.Dictionary;SWCtl.SWCtl;Shell.UIHelper;ShockwaveFlash.ShockwaveFlash;Skype.Detection;TDCCtl.TDCCtl;WMPlayer.OCX;rmocx.RealPlayer G2 Control;rmocx.RealPlayer G2 Control.1".split(";");
var d=0;for(a=f.length;d<a;d++){var l=f[d];try{var k=new ActiveXObject(l);b.push({name:l,version:k.GetVariable("$version")})}catch(q){}}navigator.plugins&&(b=b.concat(this.getRegularPlugins()));return b};a.prototype.getPlugins=function(){return window.ActiveXObject?this.getIEPlugins():this.getRegularPlugins()};a.prototype.getScreenProperties=function(){var a;var b={};var f=window.screen;for(a in f){var d=f[a];"object"!==typeof d&&(b[a]=d)}return b};a.prototype.getSystemColors=function(){var a;var b=
document.createElement("div");var f={};var d="ActiveBorder ActiveCaption AppWorkspace Background ButtonFace ButtonHighlight ButtonShadow ButtonText CaptionText GrayText Highlight HighlightText InactiveBorder InactiveCaption InactiveCaptionText InfoBackground InfoText Menu MenuText Scrollbar ThreeDDarkShadow ThreeDFace ThreeDHighlight ThreeDLightShadow ThreeDShadow Window WindowFrame WindowText".split(" ");if(window.getComputedStyle){var l=0;for(a=d.length;l<a;l++){var k=d[l];document.body.appendChild(b);
b.style.color=k;f[k]=window.getComputedStyle(b).getPropertyValue("color");document.body.removeChild(b)}return f}};a.prototype.getBattery=function(a){return navigator.getBattery?navigator.getBattery().then(function(b){return a({charging:b.charging,chargingTime:b.chargingTime,dischargingTime:b.dischargingTime,level:b.level})}):a()};a.prototype.getProperties=function(){var a=new Date;a:{try{var b=this.getCodecs();break a}catch(p){}b=void 0}var f=a.getTime()/1E3,d=document.URL,l=document.documentMode;
a:{try{var k=this.getCSSFonts();break a}catch(p){}k=void 0}a:{try{var g=this.getNavigatorProperties();break a}catch(p){}g=void 0}a:{try{var h=this.getPlugins();break a}catch(p){}h=void 0}a:{try{var c=this.getScreenProperties();break a}catch(p){}c=void 0}a:{try{var m=this.getSystemColors();break a}catch(p){}m=void 0}return{codecs:b,deviceTime:f,documentUrl:d,documentMode:l,fonts:k,navigator:g,plugins:h,screen:c,systemColors:m,timezoneOffset:a.getTimezoneOffset()}};return a}();n.exports=g}).call(this)}});
this.clearbitRequire.define({"risk/fontdetect":function(c,m,n){n.exports=function(){var h=["monospace","sans-serif","serif"],g=document.getElementsByTagName("body")[0],a=document.createElement("span");a.style.fontSize="72px";a.innerHTML="mmmmmmmmmmlli";var e={},b={},f;for(f in h)a.style.fontFamily=h[f],g.appendChild(a),e[h[f]]=a.offsetWidth,b[h[f]]=a.offsetHeight,g.removeChild(a);this.detect=function(d){var f=!1,k;for(k in h){a.style.fontFamily=d+","+h[k];g.appendChild(a);var c=a.offsetWidth!=e[h[k]]||
a.offsetHeight!=b[h[k]];g.removeChild(a);f=f||c}return f}}}});
this.clearbitRequire.define({"risk/json":function(c,m,n){c={parse:function(h){return eval("("+h+")")},stringify:function(){var h=Object.prototype.toString,g=Array.isArray||function(a){return"[object Array]"===h.call(a)},a={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"},e=function(b){return a[b]||"\\u"+(b.charCodeAt(0)+65536).toString(16).substr(1)},b=/[\\"\u0000-\u001F\u2028\u2029]/g;return function l(a){if(null==a)return"null";if("number"===typeof a)return isFinite(a)?
a.toString():"null";if("boolean"===typeof a)return a.toString();if("object"===typeof a){if("function"===typeof a.toJSON)return l(a.toJSON());if(g(a)){for(var d="[",c=0;c<a.length;c++)d+=(c?", ":"")+l(a[c]);return d+"]"}if("[object Object]"===h.call(a)){d=[];for(c in a)a.hasOwnProperty(c)&&d.push(l(c)+": "+l(a[c]));return"{"+d.join(", ")+"}"}}return'"'+a.toString().replace(b,e)+'"'}}()};n.exports=window.JSON||c}});
this.clearbitRequire.define({"risk/utils":function(c,m,n){(function(){var h=m("./json");c.onDocumentReady=function(a){var b=!1;var f=function(){if(!b)return b=!0,a()};if("complete"===document.readyState||"loading"!==document.readyState&&!document.documentElement.doScroll)return setTimeout(f);if(document.addEventListener)return document.addEventListener("DOMContentLoaded",f,!1),document.addEventListener("load",f,!1);document.attachEvent("onreadystatechange",f);return window.attachEvent("onload",f)};
var g=function(){return"Microsoft Internet Explorer"===navigator.appName&&window.XDomainRequest};c.postJSON=function(a,b,f){if(g()){var d=new XDomainRequest;d.onprogress=function(){};d.ontimeout=function(){};d.onerror=function(){}}else d=new window.XMLHttpRequest;var e=!1;var k=function(){if(!e)return e=!0,"function"===typeof f?f(d):void 0};d.onreadystatechange=function(){if(3<d.readyState)return k()};d.onload=function(){return k()};d.open("POST",a,!0);"function"===typeof d.setRequestHeader&&d.setRequestHeader("Content-Type",
"text/plain;charset=UTF-8");return d.send(h.stringify(b))};c.environment=("undefined"!==typeof localStorage&&null!==localStorage?localStorage.CB_ENV:void 0)||"production";var a={local:{"https://risk.clearbit.com":""},development:{"https://risk.clearbit.com":"https://risk.dev.clearbit.io"},staging:{"https://risk.clearbit.com":"https://risk.staging.clearbit.io"},edge:{"https://risk.clearbit.com":"https://risk-edge.clearbit.com"}};c.endpoint=function(e){var b,f;return null!=(b=null!=(f=a[c.environment])?
f[e]:void 0)?b:e}}).call(this)}});
this.clearbitRequire.define({"risk/webrtc":function(c,m,n){(function(){var c=function(){function c(){}var a=window.RTCPeerConnection||window.mozRTCPeerConnection||window.webkitRTCPeerConnection;var e=/([0-9]{1,3}(\.[0-9]{1,3}){3}|[a-f0-9]{1,4}(:[a-f0-9]{1,4}){7})/;c.isSupported=function(){return!!a};c.getIPs=function(a){try{return this.getIPsUnguarded(a)}catch(f){}};c.getIPsUnguarded=function(b){var f={};var d=function(a){try{var d=e.exec(a)[1];if(!f[d])return f[d]=!0,b(d)}catch(r){}};var c=new a({iceServers:[{urls:"stun:stun.services.mozilla.com",
url:"stun:stun.services.mozilla.com"}]},{optional:[{RtpDataChannels:!0}]});c.onicecandidate=function(a){if(a.candidate)return d(a.candidate.candidate)};c.createDataChannel("");c.createOffer(function(a){return c.setLocalDescription(a,function(){},function(){})},function(){});if(c.localDescription&&"string"===typeof c.localDescription.sdp)return setTimeout(function(){return c.localDescription.sdp.split("\n").forEach(function(a){if(0===a.indexOf("a=candidate:"))return d(a)})},1E3)};return c}();n.exports=
c}).call(this)}});
(function(){var c=function(a,b){return function(){return a.apply(b,arguments)}};var m=clearbitRequire("risk/webrtc");var n=clearbitRequire("risk/fingerprint");var h=clearbitRequire("risk/utils");var g=h.onDocumentReady;var a=h.postJSON;var e=h.endpoint;var b=function(){function b(){this.sendFingerprint=c(this.sendFingerprint,this);this.onClientIP=c(this.onClientIP,this);this.onFingerprint=c(this.onFingerprint,this);try{this.clientIPs=[],m.isSupported()&&m.getIPs(this.onClientIP),n.calculate(this.onFingerprint)}finally{setTimeout(this.sendFingerprint,
1E3)}}b.prototype.endpoint=e("https://risk.clearbit.com");b.prototype.onFingerprint=function(a){this.fingerprint=a};b.prototype.onClientIP=function(a){return this.clientIPs.push(a)};b.prototype.sendFingerprint=function(){if(this.fingerprint)return this.fingerprint.clientIPs=this.clientIPs,a(this.endpoint+"/v1/fingerprint",this.fingerprint)};return b}();g(function(){return new b})}).call(this);
